// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eghfhqkfrzofoqxrqkam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnaGZocWtmcnpvZm9xeHJxa2FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjAyMDYsImV4cCI6MjA2NDUzNjIwNn0.9w3V4zGUnurzWGb3CGZxOFCrAWaaaqBs92wnyH-hrKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);